// <auto-generated />
using System;
using InsuranceCompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceCompany.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612174226_initail Migrate")]
    partial class initailMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceCompany.Models.Authentication.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Authentication.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PANNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Communications.EmailNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("EmailNotifications");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("ClaimDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssuedPolicyId")
                        .HasColumnType("int");

                    b.Property<string>("OfficerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("IssuedPolicyId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.IssuedPolicy", b =>
                {
                    b.Property<int>("IssuedPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssuedPolicyId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsurancePolicyPolicyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDocumentEmailed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIssuedCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IssuedPolicyId");

                    b.HasIndex("InsurancePolicyPolicyId");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("ProposalId")
                        .IsUnique()
                        .HasFilter("[ProposalId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("IssuedPolicies");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("QuoteId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.AddOn", b =>
                {
                    b.Property<int>("AddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddOnId"));

                    b.Property<string>("AddOnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AdditionalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AddOnId");

                    b.ToTable("AddOns");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CoverageDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PolicyDurationDays")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VehicleCategoryCategoryId")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("VehicleCategoryCategoryId");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.PolicyAddOn", b =>
                {
                    b.Property<int>("PolicyAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyAddOnId"));

                    b.Property<int>("AddOnId")
                        .HasColumnType("int");

                    b.Property<int?>("InsurancePolicyPolicyId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("PolicyAddOnId");

                    b.HasIndex("AddOnId");

                    b.HasIndex("InsurancePolicyPolicyId");

                    b.ToTable("PolicyAddOns");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.VehicleCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("VehicleCategories");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Proposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalId"));

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsurancePolicyPolicyId")
                        .HasColumnType("int");

                    b.Property<string>("OfficerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleAge")
                        .HasColumnType("int");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("int");

                    b.HasKey("ProposalId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("InsurancePolicyPolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.ProposalAddOn", b =>
                {
                    b.Property<int>("ProposalAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalAddOnId"));

                    b.Property<int>("AddOnId")
                        .HasColumnType("int");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.HasKey("ProposalAddOnId");

                    b.HasIndex("AddOnId");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalAddOns");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.ProposalDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalDocuments");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<decimal>("AddOnCost")
                        .HasColumnType("decimal(18 , 2)");

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int?>("GeneratorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailed")
                        .HasColumnType("bit");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("RiskFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VehicleAgeFactor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("QuoteId");

                    b.HasIndex("GeneratorUserId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Authentication.User", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Authentication.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Communications.EmailNotification", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.Claim", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Operations.IssuedPolicy", "IssuedPolicy")
                        .WithMany("Claims")
                        .HasForeignKey("IssuedPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceCompany.Models.Authentication.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy");

                    b.HasOne("InsuranceCompany.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedPolicy");

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.IssuedPolicy", b =>
                {
                    b.HasOne("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", "InsurancePolicy")
                        .WithMany()
                        .HasForeignKey("InsurancePolicyPolicyId");

                    b.HasOne("InsuranceCompany.Models.Operations.Payment", "Payment")
                        .WithOne("IssuedPolicy")
                        .HasForeignKey("InsuranceCompany.Models.Operations.IssuedPolicy", "PaymentId");

                    b.HasOne("InsuranceCompany.Models.Proposals.Proposal", "Proposal")
                        .WithOne("IssuedPolicy")
                        .HasForeignKey("InsuranceCompany.Models.Operations.IssuedPolicy", "ProposalId");

                    b.HasOne("InsuranceCompany.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("InsurancePolicy");

                    b.Navigation("Payment");

                    b.Navigation("Proposal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.Payment", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Proposals.Proposal", "Proposal")
                        .WithMany("Payments")
                        .HasForeignKey("ProposalId");

                    b.HasOne("InsuranceCompany.Models.Proposals.Quote", "Quote")
                        .WithMany("Payments")
                        .HasForeignKey("QuoteId");

                    b.Navigation("Proposal");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Authentication.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("InsuranceCompany.Models.PolicyManagement.VehicleCategory", "VehicleCategory")
                        .WithMany("InsurancePolicies")
                        .HasForeignKey("VehicleCategoryCategoryId");

                    b.Navigation("Creator");

                    b.Navigation("VehicleCategory");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.PolicyAddOn", b =>
                {
                    b.HasOne("InsuranceCompany.Models.PolicyManagement.AddOn", "AddOn")
                        .WithMany("PolicyAddOns")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", "InsurancePolicy")
                        .WithMany("PolicyAddOns")
                        .HasForeignKey("InsurancePolicyPolicyId");

                    b.Navigation("AddOn");

                    b.Navigation("InsurancePolicy");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Proposal", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Authentication.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId");

                    b.HasOne("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", "InsurancePolicy")
                        .WithMany()
                        .HasForeignKey("InsurancePolicyPolicyId");

                    b.HasOne("InsuranceCompany.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("InsurancePolicy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.ProposalAddOn", b =>
                {
                    b.HasOne("InsuranceCompany.Models.PolicyManagement.AddOn", "AddOn")
                        .WithMany()
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceCompany.Models.Proposals.Proposal", "Proposal")
                        .WithMany("ProposalAddOns")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.ProposalDocument", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Proposals.Proposal", "Proposal")
                        .WithMany("ProposalDocuments")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Quote", b =>
                {
                    b.HasOne("InsuranceCompany.Models.Authentication.User", "Generator")
                        .WithMany()
                        .HasForeignKey("GeneratorUserId");

                    b.HasOne("InsuranceCompany.Models.Proposals.Proposal", "Proposal")
                        .WithOne("Quote")
                        .HasForeignKey("InsuranceCompany.Models.Proposals.Quote", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generator");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Authentication.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.IssuedPolicy", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Operations.Payment", b =>
                {
                    b.Navigation("IssuedPolicy");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.AddOn", b =>
                {
                    b.Navigation("PolicyAddOns");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.InsurancePolicy", b =>
                {
                    b.Navigation("PolicyAddOns");
                });

            modelBuilder.Entity("InsuranceCompany.Models.PolicyManagement.VehicleCategory", b =>
                {
                    b.Navigation("InsurancePolicies");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Proposal", b =>
                {
                    b.Navigation("IssuedPolicy");

                    b.Navigation("Payments");

                    b.Navigation("ProposalAddOns");

                    b.Navigation("ProposalDocuments");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("InsuranceCompany.Models.Proposals.Quote", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
